# Generated by Django 4.2.7 on 2023-12-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="profile_images/default.jpg", upload_to="profile_pics"),
        ),
    ]
